# Generated by Django 4.2.6 on 2023-10-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_modified',
            field=models.DateTimeField(),
        ),
    ]
