# Generated by Django 4.2.6 on 2023-10-23 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0007_visitedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
