# Generated by Django 4.2.6 on 2023-10-25 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_alter_visitedin_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitedin',
            options={'ordering': ['year']},
        ),
        migrations.AddField(
            model_name='profile',
            name='least_liked',
            field=models.ManyToManyField(blank=True, related_name='least_liked_of', to='location.location'),
        ),
        migrations.AlterField(
            model_name='visitedin',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='location.location'),
        ),
        migrations.AlterField(
            model_name='visitedin',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'january'), (2, 'february'), (3, 'march'), (4, 'april'), (5, 'may'), (6, 'june'), (7, 'july'), (8, 'august'), (9, 'september'), (10, 'october'), (11, 'november'), (12, 'december')], null=True),
        ),
    ]
