# Generated by Django 4.2.6 on 2023-10-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_alter_visitedin_options_profile_least_liked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_least_liked',
            field=models.BooleanField(default=False, help_text='It is possible to "unlike" a location. Enable this field to hide the least-liked locations.'),
        ),
    ]
