# Generated by Django 4.2.6 on 2023-10-27 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0010_profile_hide_least_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='family',
            field=models.ManyToManyField(blank=True, help_text='family members', related_name='family_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
