# Generated by Django 4.2.6 on 2023-11-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_alter_profile_family'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__name', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='visitedin',
            options={'ordering': ['location', 'year']},
        ),
    ]
