# Generated by Django 4.2.6 on 2023-11-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='thumbnail',
        ),
    ]
