# Generated by Django 4.2.6 on 2023-11-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0014_remove_media_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['visibility', '-date_modified'], 'verbose_name_plural': 'media'},
        ),
        migrations.AddField(
            model_name='list',
            name='template',
            field=models.CharField(choices=[('l', 'list'), ('t', 'trip')], default='t', max_length=1),
        ),
    ]
