# Generated by Django 4.2.6 on 2023-11-18 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_alter_media_options_list_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='listlocation',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.media'),
        ),
    ]
