# Generated by Django 4.2.6 on 2023-11-18 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0016_listlocation_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='media', to='location.location'),
        ),
    ]
