# Generated by Django 4.2.6 on 2023-11-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_alter_media_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='order',
            field=models.CharField(choices=[('date', 'date_added'), ('distance', 'distance'), ('region', 'region')], default='distance', max_length=16),
        ),
    ]
