# Generated by Django 4.2.6 on 2023-11-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_alter_profile_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='hide_from_filterlist',
            field=models.BooleanField(default=False),
        ),
    ]
