# Generated by Django 4.2.6 on 2023-11-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_tag_hide_from_filterlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='maps_permission',
            field=models.BooleanField(default=False, help_text='Give permission to load Google Maps map on location detail page'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hide_least_liked',
            field=models.BooleanField(default=False, help_text='It is possible to "unlike" a location. Enable this field to hide the least-liked locations'),
        ),
    ]
