# Generated by Django 4.2.6 on 2023-12-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0021_profile_maps_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ignored_tags',
            field=models.ManyToManyField(blank=True, related_name='ignored_by', to='location.tag'),
        ),
    ]
