# Generated by Django 4.2.9 on 2024-06-14 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_squashed_0022_profile_ignored_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='location.category'),
        ),
    ]
