# Generated by Django 4.2.9 on 2024-06-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0023_alter_location_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='chain',
        ),
        migrations.AddField(
            model_name='location',
            name='chain',
            field=models.ManyToManyField(blank=True, related_name='locations', to='location.chain'),
        ),
    ]
