# Generated by Django 4.2.9 on 2024-07-03 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0024_remove_location_chain_location_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listlocation',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.media'),
        ),
    ]
