# Generated by Django 4.2.9 on 2024-07-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0025_alter_listlocation_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='map',
            field=models.BooleanField(default=False, help_text='Show map on list page'),
        ),
    ]
