# Generated by Django 5.0.6 on 2024-07-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0026_list_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='listlocation',
            name='show_on_route',
            field=models.BooleanField(default=True),
        ),
    ]
