# Generated by Django 5.1 on 2024-09-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0029_link_primary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-primary', 'url']},
        ),
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, help_text='Title of link, optional', max_length=255),
        ),
    ]
