# Generated by Django 5.1 on 2024-09-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0031_alter_location_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='website',
        ),
    ]
