# Generated by Django 5.1 on 2024-09-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0032_remove_location_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='filter_by_distance',
            field=models.BooleanField(default=True, help_text='Allow to filter locations by distance'),
        ),
    ]
