# Generated by Django 5.1 on 2024-09-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0034_alter_profile_filter_by_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
