# Generated by Django 5.1 on 2024-09-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0035_region_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='add order to countries for sorting in distance sorted overview. only works for countries'),
        ),
    ]
