# Generated by Django 5.1 on 2024-11-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0037_description_location_descriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Markdown is supported'),
        ),
    ]
