# Generated by Django 5.1 on 2024-11-11 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0038_alter_comment_options_alter_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='least_liked',
            new_name='dislike',
        ),
    ]
