# Generated by Django 5.1 on 2024-11-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0039_rename_least_liked_profile_dislike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='title',
            new_name='name',
        ),
    ]
