# Generated by Django 5.1 on 2024-12-28 17:41

from django.db import migrations
import random, string


class Migration(migrations.Migration):
    def create_clothing_sizes(apps, schema_editor):
        #User = get_user_model()
        User = apps.get_model('auth', 'User')
        user = None
        try:
            user = User.objects.get(username='arnecoomans')
        except User.DoesNotExist:
            if User.objects.count() == 0:
                print("No users found, creating superuser 'admin'")
                user = User.objects.create_superuser('admin', 'admin@example.com', ''.join(random.choices(string.ascii_letters + string.digits, k=16)))
            else:
                user = User.objects.first()    
        print(f"Using user '{user}' for creating clothing sizes")

        size = apps.get_model('location', 'Size')
        sizes = [('?', 'Unsure'), ('xxs', 'Extra Extra Small (1-10)'), ('xs', 'Extra Small (10-25)'), ('s', 'Small (25-50)'), ('m', 'Medium (50-100)'), ('l', 'Large (100-150)'), ('xl', 'Extra Large (150-250)'), ('xxl', 'Extra Extra Large (250+)')]
        for sizeobj in sizes:
            size.objects.get_or_create(
                slug=sizeobj[0], 
                defaults={
                    'name': sizeobj[1], 
                    'user': user,
                    }
            )

    dependencies = [
        ('location', '0043_remove_size_display_name_size_slug_alter_size_name'),
    ]

    operations = [
        migrations.RunPython(create_clothing_sizes),
    ]
