# Generated by Django 5.1.4 on 2025-01-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0045_auto_20241228_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='is_editable',
            field=models.BooleanField(default=True, help_text='should this list appear at locations when adding a location to a list'),
        ),
    ]
