# Generated by Django 5.1.4 on 2025-01-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0046_list_is_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notes',
            field=models.TextField(blank=True, help_text='personal notes'),
        ),
    ]
