# Generated by Django 5.1.5 on 2025-08-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0047_profile_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('url_format', models.CharField(help_text='Use {address} as placeholder', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='navigationapps',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='location.navigationapps'),
        ),
    ]
