# Generated by Django 5.1.5 on 2025-08-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0048_navigationapps_profile_navigationapps'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationapps',
            name='default_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
