# Generated by Django 5.1.5 on 2025-09-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0050_seed_navigationapps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationapps',
            options={'verbose_name': 'Navigation app', 'verbose_name_plural': 'Navigation apps'},
        ),
    ]
