# Generated by Django 5.2.6 on 2025-09-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0051_alter_navigationapps_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='chain',
            new_name='chains',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='link',
            new_name='links',
        ),
    ]
