# Generated by Django 5.2.6 on 2025-09-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0052_rename_chain_location_chains_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
    ]
