# Generated by Django 5.2.6 on 2025-10-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0053_remove_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='cached_average_distance_to_center',
            field=models.FloatField(blank=True, editable=False, help_text='cached average distance to center of this region (in km)', null=True),
        ),
    ]
