# Generated by Django 5.2.7 on 2025-10-04 20:35

import cmnsd.models.cmnsd_basemodel
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0054_region_cached_average_distance_to_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='comment',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('c', 'Concept'), ('p', 'Published'), ('r', 'Revoked'), ('x', 'Deleted')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
