# Generated by Django 5.2.7 on 2025-10-04 20:52

import cmnsd.models.cmnsd_basemodel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0059_regenerate_all_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='listlocation',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='visitedin',
            name='token',
            field=models.CharField(blank=True, default=cmnsd.models.cmnsd_basemodel.generate_public_id, editable=False, help_text='Short unique ID for public URL use', max_length=20, unique=True),
        ),
    ]
