# Generated by Django 5.2.7 on 2025-10-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0060_alter_comment_token_alter_description_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': 'Description', 'verbose_name_plural': 'Descriptions'},
        ),
    ]
