# Generated by Django 5.2.7 on 2025-10-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0061_alter_description_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-list_as', 'name']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='visibility',
            field=models.CharField(choices=[('p', 'public'), ('c', 'commmunity'), ('f', 'family'), ('q', 'private')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='description',
            name='visibility',
            field=models.CharField(choices=[('p', 'public'), ('c', 'commmunity'), ('f', 'family'), ('q', 'private')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='link',
            name='visibility',
            field=models.CharField(choices=[('p', 'public'), ('c', 'commmunity'), ('f', 'family'), ('q', 'private')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='list',
            name='visibility',
            field=models.CharField(choices=[('p', 'public'), ('c', 'commmunity'), ('f', 'family'), ('q', 'private')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='listlocation',
            name='visibility',
            field=models.CharField(choices=[('p', 'public'), ('c', 'commmunity'), ('f', 'family'), ('q', 'private')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='location',
            name='visibility',
            field=models.CharField(choices=[('p', 'public'), ('c', 'commmunity'), ('f', 'family'), ('q', 'private')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='media',
            name='visibility',
            field=models.CharField(choices=[('p', 'public'), ('c', 'commmunity'), ('f', 'family'), ('q', 'private')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='visibility',
            field=models.CharField(choices=[('p', 'public'), ('c', 'commmunity'), ('f', 'family'), ('q', 'private')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='visitedin',
            name='visibility',
            field=models.CharField(choices=[('p', 'public'), ('c', 'commmunity'), ('f', 'family'), ('q', 'private')], default='p', max_length=1),
        ),
    ]
