# Generated by Django 5.2.7 on 2025-10-15 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0062_alter_tag_options_alter_comment_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='location.location'),
        ),
    ]
