# Generated by Django 5.2.7 on 2025-10-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0063_alter_listlocation_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ['-date_created']},
        ),
    ]
