# Generated by Django 5.2.7 on 2025-10-17 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0064_alter_description_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='description',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='location.location'),
            preserve_default=False,
        ),
    ]
