# Generated by Django 5.2.7 on 2025-10-17 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0065_remove_location_descriptions_description_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='location.location'),
        ),
    ]
