# Generated by Django 5.2.7 on 2025-10-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0066_alter_description_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='description',
            unique_together={('location', 'visibility')},
        ),
    ]
