# Generated by Django 5.2.8 on 2025-11-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0067_alter_description_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this tag, why it is relevant'),
        ),
    ]
